
services:
  postgres:
    image: postgres:latest
    container_name: postgres-library
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    ports:
      - 5433:5432
    volumes:
      - library:/var/lib/postgresql/data
volumes:
  library: